project:
  type: website

website:
  title: "Les vélos et vélos en libre-service à Montpellier"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - supp.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



