name: Deploy to GitHub Pages

on:
  push:
    branches:
      - feature-website  # ou main si c'est la branche par défaut

permissions:
  contents: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2      
        
      - name: Set up ffmpeg  # Mise en place du module pour créer des vidéos
        uses: FedericoCarboni/setup-ffmpeg@v3

      - name: Install Python and Dependencies # Instalation de Python + des librairies nécessaires (inclues dans requirements.txt)
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      - run: python -m pip install --upgrade pip
      - run: pip install jupyter
      - run: pip install -r requirements.txt
      
      - name: Build and deploy with Quarto
        run: quarto render  # adapte si nécessaire pour construire le site
      
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
