project:
  type: website
  output-dir: .   # Dossier racine

website:
  title: "Flux de vélos à Montpellier"
  navbar:
    left:
      - text: "Prévisions"
        href: index.qmd
      - text: "Trafic"
        href: about.qmd
      - text: "données"
        href: contact.qmd

output:
    html:
      theme: cosmo
      css: styles/custom.css
      toc: true
