project:
  type: website
  output-dir: .   # Dossier racine

website:
  # Pas de titre ici
  navbar:
    left:
      - text: "Accueil"
        href: accueil.qmd
      - text: "Prévisions"
        href: index.qmd
      - text: "Densité du traffic"
        href: density.qmd
      - text: "Traffic"
        href: traffic.qmd
      - text: "Disponibilité des vélos"
        href: dispo.qmd
      - text: "données"
        href: contact.qmd

output:
    html:
      theme: cosmo
      css: styles/custom.css
      toc: true
