project:
  type: website
  output-dir: .   # Dossier racine

website:
  # Pas de titre ici
  navbar:
    left:
      - text: "Accueil"
        href: index.qmd
      - text: "Densité du trafic"
        href: density.qmd
      - text: "Trafic"
        href: trafic.qmd
      - text: "Disponibilité des vélos"
        href: dispo.qmd
      - text: "Étude"
        href: "etude.qmd"
      - text: "Données"
        href: donnees.qmd
      - icon: github
        href: https://github.com/LucineBonnnefont/projet-dev


output:
  html:
    theme: cosmo
    css: styles/custom.css
    include-after-body: footer.qmd
