project:
  type: website

website:
  title: "Mon Site Web"
  navbar:
    left:
      - text: "Accueil"
        href: index.qmd
      - text: "À propos"
        href: about.qmd
      - text: "Contact"
        href: contact.qmd

output:
    html:
      theme: cosmo
      css: styles/custom.css
      toc: true
