project:
  type: website
  output-dir: .   # Dossier racine

website:
  title: |
    <div style="display: flex; align-items: center;">
      <img src="images/logo.png" alt="Logo Montpelli'Cycle" style="width: 50px; height: auto; margin-right: 10px;">
      Flux de vélos à Montpellier
    </div>
  navbar:
    left:
      - text: "Montpelli'Cycle"
        href: accueil.qmd
      - text: "Prévisions"
        href: index.qmd
      - text: "Densité du traffic"
        href: density.qmd
      - text: "Traffic"
        href: traffic.qmd
      - text: "Disponibilité des vélos"
        href: dispo.qmd
      - text: "données"
        href: contact.qmd

output:
    html:
      theme: cosmo
      css: styles/custom.css
      toc: true
