name: Render Disponibilités vélos dans Montpellier

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"  # Automatisation toutes les 15 minutes

jobs:
  render-dispo:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Python and Dependencies
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt

      - name: Render Dispo.html
        working-directory: docs
        run: quarto render dispo.qmd

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull
          git add docs/
          git commit -m "Update dispo.html with real time data"
          git push
          
